#### general settings
name: 01_IRN_DB_x2_scratch_DIV2K
use_tb_logger: true
model: IRN
distortion: sr
scale: 2
gpu_ids: [0]

#### network structures
network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8]
  scale: 2
  init: xavier


#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT_rcan
    dataroot_GT: /home/data/disk2/wsq/Datasets/DIV2K/DIV2K_train_HR_sub
    dataroot_LQ: /home/data/disk2/wsq/Datasets/DIV2K/DIV2K_train_LR_bicubic/X2_sub
    # dataroot_GT: dataset/DIV2K_scale_sub/GT
    # dataroot_LQ: dataset/DIV2K_scale_sub/LR

    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 2
    GT_size: 144
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: urban100
    mode: LQGT_rcan
    dataroot_GT: /home/data/disk2/wsq/Datasets/DIV2K/DIV2K_train_HR_sub
    dataroot_LQ: /home/data/disk2/wsq/Datasets/DIV2K/DIV2K_train_LR_bicubic/X2_sub
    # dataroot_GT: dataset/DIV2K_valid_sub/GT
    # dataroot_LQ: dataset/DIV2K_valid_sub/LR

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.999
  niter: 1000000
  warmup_iter: -1  # no warm up
  T_period: [1000000]
  restarts: [1000000]
  restart_weights: [1]
  eta_min: !!float 1e-7
  lr_gamma: 0.5
  clear_state: 1000000
  pixel_criterion_forw: l2
  pixel_criterion_back: l1
  pixel_criterion: l2
  pixel_weight: 1.0
  lambda_fit_forw: 4.
  lambda_rec_back: 1
  lambda_ce_forw: 1
  manual_seed: 10
  val_freq: 5000
  gradient_clipping: 10

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 500
